### ISSUE TITLE
KeyError: u'request' when try to update list by AJAX?

### ISSUE THREAD

**Issue by NogerbekNurzhan** [shtalinberg/django-el-pagination#104]
Hello! :) First of all THANK YOU for this wonderful project!

I use `django==1.11.5` and `django-el-pagination==3.1.0`.

I have list of documents and I use pagination on scroll to that list.

Also I have form to create new document. After submit the form, if it successful, I want to update list of documents by ajax. I have next error and it seems to I have conflict with _django-el-pagination_. Where I make mistake?

**views.py:**
```
class DocumentCreate(CreateView):
    template_name = 'documents/create_document.html'
    form_class = DocumentCreateForm

    def get(self, request, *args, **kwargs):
        data = dict()
        context = {
            'document_create_form': DocumentCreateForm(),
        }
        data['html_form'] = render_to_string('documents/create_document.html', context, request=request)
        return JsonResponse(data)

    def form_valid(self, form):
        new_document = form.save(commit=False)
        new_document.author_id = self.request.user
        new_document.save()
        form.save()
        data = dict()
        data['form_is_valid'] = True
        context = {
            'documents': Document.objects.filter(parent__isnull=True)
        }
        data['html_documents'] = render_to_string('documents/documents.html', context)
        return JsonResponse(data)
```

**ERROR:**
```
Traceback (most recent call last):
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/views/generic/edit.py", line 217, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/views/generic/edit.py", line 183, in post
    return self.form_valid(form)
  File "/Applications/Projects/web/my_project/documents/views.py", line 150, in form_valid
    data['html_documents'] = render_to_string('documents/documents.html', context)
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/el_pagination/templatetags/el_pagination_tags.py", line 308, in render
    context['request'], querystring_key, default=default_number)
  File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/template/context.py", line 87, in __getitem__
    raise KeyError(key)
KeyError: u'request'
```
As you can see error happens in this 2 lines:
`data['html_documents'] = render_to_string('documents/documents.html', context)` (views.py)
and
`context['request'], querystring_key, default=default_number)` (el_pagination_tags.py)

Also I notice that in database new documents was created. Do you have any ideas how to fix this problem?

**Comment by shtalinberg** [comment]
render_to_string(template_name, context=None, request=None, using=None)
add request as param to render_to_string

It's bug-tracker, please, use StackOverflow for question like this

**Comment by NogerbekNurzhan** [comment]
I tried to use code which you advised but it didn't work for me =(

**Comment by int-ua** [comment]
I had a similar situation after upgrading to the new `TEMPLATES` setting and not having `django.template.context_processors.request` in `[OPTIONS][context_processors]`.
