### ISSUE TITLE
Failed building wheel for django-el-pagination

### ISSUE THREAD

**Issue by bashu** [shtalinberg/django-el-pagination#16]
```shell
Collecting django-el-pagination
  Downloading django-el-pagination-2.1.1.tar.gz (66kB)
    100% |████████████████████████████████| 69kB 372kB/s
Requirement already satisfied (use --upgrade to upgrade): django>=1.4.0 in /Users/bashu/.virtualenvs/demo/lib/python2.7/site-packages (from django-el-pagination)
Building wheels for collected packages: django-el-pagination
  Running setup.py bdist_wheel for django-el-pagination
  Complete output from command /Users/bashu/.virtualenvs/demo/bin/python -c "import setuptools;__file__='/private/var/folders/Xe/XeGoWV6IHaOrxd+aEKCB-U+++TM/-Tmp-/pip-build-SJVx9J/django-el-pagination/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/Xe/XeGoWV6IHaOrxd+aEKCB-U+++TM/-Tmp-/tmpNwlNrypip-wheel-:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/Xe/XeGoWV6IHaOrxd+aEKCB-U+++TM/-Tmp-/pip-build-SJVx9J/django-el-pagination/setup.py", line 83, in <module>
      install_requires=install_requires,
    File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 137, in setup
      ok = dist.parse_command_line()
    File "/Users/bashu/.virtualenvs/demo/lib/python2.7/site-packages/setuptools/dist.py", line 299, in parse_command_line
      result = _Distribution.parse_command_line(self)
    File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 467, in parse_command_line
      args = self._parse_command_opts(parser, args)
    File "/Users/bashu/.virtualenvs/demo/lib/python2.7/site-packages/setuptools/dist.py", line 609, in _parse_command_opts
      nargs = _Distribution._parse_command_opts(self, parser, args)
    File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 523, in _parse_command_opts
      cmd_class = self.get_command_class(command)
    File "/Users/bashu/.virtualenvs/demo/lib/python2.7/site-packages/setuptools/dist.py", line 429, in get_command_class
      ep.require(installer=self.fetch_build_egg)
    File "/Users/bashu/.virtualenvs/demo/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2217, in require
      reqs = self.dist.requires(self.extras)
    File "/Users/bashu/.virtualenvs/demo/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2462, in requires
      dm = self._dep_map
    File "/Users/bashu/.virtualenvs/demo/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2686, in _dep_map
      self.__dep_map = self._compute_dependencies()
    File "/Users/bashu/.virtualenvs/demo/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2696, in _compute_dependencies
      current_req = packaging.requirements.Requirement(req)
    File "/Users/bashu/.virtualenvs/demo/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 94, in __init__
      requirement_string[e.loc:e.loc + 8]))
  pkg_resources._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'; sys.pl'"

  ----------------------------------------
  Failed building wheel for django-el-pagination
Failed to build django-el-pagination
Installing collected packages: django-el-pagination
  Running setup.py install for django-el-pagination
Successfully installed django-el-pagination-2.1.1
```

**Comment by bashu** [comment]
on my side...
