### ISSUE TITLE
 KeyError  'request'

### ISSUE THREAD

**Issue by korolr** [shtalinberg/django-el-pagination#39]
KeyError at /
'request'
Request Method:	GET
Request URL:	http://127.0.0.1:8000/
Django Version:	1.9.7
Exception Type:	KeyError
Exception Value:	
'request'
Exception Location:	/Users/admin/Desktop/django/da/lib/python3.5/site-packages/django/template/context.py in __getitem__, line 77
Python Executable:	/Users/admin/Desktop/django/da/bin/python3
Python Version:	3.5.1
Python Path:	
['/Users/admin/Desktop/django/da/bin/blog',
 '/Users/admin/Desktop/django/da/lib/python35.zip',
 '/Users/admin/Desktop/django/da/lib/python3.5',
 '/Users/admin/Desktop/django/da/lib/python3.5/plat-darwin',
 '/Users/admin/Desktop/django/da/lib/python3.5/lib-dynload',
 '/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5',
 '/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/plat-darwin',
 '/Users/admin/Desktop/django/da/lib/python3.5/site-packages']

And settings

       'OPTIONS': {
            'context_processors': [
                'django.core.context_processors.request',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],

**Comment by shtalinberg** [comment]
I need full log....
Do you have two request in  context_processors ??
 'context_processors': [
            'django.core.context_processors.request',
            'django.template.context_processors.request',

**Comment by korolr** [comment]
I'm just trying to learn Django and somehow fix a problem  :)

Internal Server Error: /
Traceback (most recent call last):
  File "/Users/admin/Desktop/django/da/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/admin/Desktop/django/da/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/admin/Desktop/django/da/bin/blog/article/views.py", line 13, in articles
    return render_to_response('articles.html', {'articles': Article.objects.all().order_by('-article.article_date')})
  File "/Users/admin/Desktop/django/da/lib/python3.5/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Users/admin/Desktop/django/da/lib/python3.5/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/Users/admin/Desktop/django/da/lib/python3.5/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/Users/admin/Desktop/django/da/lib/python3.5/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/Users/admin/Desktop/django/da/lib/python3.5/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/Users/admin/Desktop/django/da/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/Users/admin/Desktop/django/da/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/admin/Desktop/django/da/lib/python3.5/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/Users/admin/Desktop/django/da/lib/python3.5/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/Users/admin/Desktop/django/da/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/Users/admin/Desktop/django/da/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/admin/Desktop/django/da/lib/python3.5/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/Users/admin/Desktop/django/da/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/Users/admin/Desktop/django/da/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/admin/Desktop/django/da/lib/python3.5/site-packages/el_pagination/templatetags/el_pagination_tags.py", line 307, in render
    context['request'], querystring_key, default=default_number)
  File "/Users/admin/Desktop/django/da/lib/python3.5/site-packages/django/template/context.py", line 77, in __getitem__
    raise KeyError(key)
KeyError: 'request'

**Comment by shtalinberg** [comment]
Use render_to_response with RequestContext
render_to_response(
        template, context, context_instance=RequestContext(request))

**Comment by korolr** [comment]
thx its work
